### ISSUE TITLE
System.TimeoutException: Timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by thisjustin816** [MaxMelcher/AzureDevOps.WikiPDFExport#40] opened 2021-01-14 16:42 UTC
Getting the following output when running the tool on a fairly large wiki:

```console
ERR: Something bad happend.
System.TimeoutException: Timeout of 30000 ms exceeded
   at PuppeteerSharp.Helpers.TaskHelper.<>c__DisplayClass2_0.<WithTimeout>b__0()
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken)
   at PuppeteerSharp.DOMWorld.SetContentAsync(String html, NavigationOptions options)
   at azuredevops_export_wiki.WikiPDFExporter.Export() in D:\Git\WikiPDFExport\AzureDevOps.WikiPDFExport\WikiPDFExporter.cs:line 132
```

Here's the full command. First encountered on v2.6.0 and still getting it after updating to v2.7.1. I'm running it in an Azure Pipelines build with this set of PS commands:

```powershell
    $version = 'v2.7.1'
    $url = "https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/releases/download/$version/azuredevops-export-wiki.exe"
    
    $output = "azuredevops-export-wiki.exe"

    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest -Uri $url -OutFile $output

    ./azuredevops-export-wiki.exe -d -b -m --disableTelemetry -o "$(Build.ArtifactStagingDirectory)\wiki.pdf"
```

**Comment by MaxMelcher** [comment] 2021-01-20 10:53
It tries to download the mermaid component and then runs into a timeout. No internet on the build server? proxy?
Do you have mermaid graphs or why did you specify -m?

**Comment by thisjustin816** [comment] 2021-01-20 16:51
This is running on a hosted agent so the environment is fine. It worked perfectly up until a couple weeks ago. And yeah, there are mermaid graphs. Not sure why this was closed.

**Comment by MaxMelcher** [comment] 2021-01-20 16:59
need to restructure my workflow - I closed this to see what is open, might need to add tags to this project.

Not sure how I can help you here because I cannot reproduce it. 
By the way, there is a build task now so you dont have to maintain the powershell script, just in case you want to simplify: https://github.com/rfennell/vNextBuild/wiki/Wiki-PdfExport-Task/

**Closed** 2021-03-14 13:07 UTC
Labels: question
